### ISSUE TITLE
BlendshapeMaker example data

### ISSUE THREAD

**Issue by jerenchen** [diegothomas/Avatar-generation-3DRW2019-#1]
Hello! 

I've just created a github project (https://github.com/jerenchen/deformxfer) for my C++ implementation, which was largely based on your wonderful Python impl (thank you!) I'm also fetching your project repo for the example data when building my demo.

I wonder would you be able to take a look at the said project and let me know if you have any comments/concerns? I'd be happy to acknowledge any individuals for their contribution.

Thank you,
Jeren

**Comment by diegothomas** [comment]
Hi,

Great work! It is a nice project.
Only comment: it would be great to have a small interface to select the landmarks.

**Comment by jerenchen** [comment]
Thanks! Being able to specify landmark mapping and observe the result is a neat idea, something to implement for my next iteration 🙂

**Comment by jerenchen** [comment]
Closing as it's no longer an "issue". Thanks again!
