### ISSUE TITLE
BS generation from head template to whole body avatar model

### ISSUE THREAD

**Issue by jiawenzzz** [diegothomas/Avatar-generation-3DRW2019-#2]
Hello, I noticed that the avatar model in your paper and provided in this project only contain the head (and neck), I tried a new avatar model with only head, it worked well. 

However, when I tried to generate BS from head templates to whole-body avatar model (still select the 51 facial landmarks), something got wrong. I guess error occurred in the step of deforming avatar neutral model towards source neutral model. Maybe I could constrain the avatar model to head part during non-rigid deformation? Not sure if it makes sense. Any sugguestions? 

Thanks,
Jiawen

**Comment by diegothomas** [comment]
Hi Jiawen, 
Thank you for your interest in our project. 
We focused only on warping head model (defined the landmarks only for the head) and did not test on full body avatar (which is a nice follow up task to do!).
Maybe you can try to adjust some hyperparameters in the algorithm, such as weights for smoothness, or landmark constraints. (like ws = 1; wi = 0.001; wc = 0.1; wcons = 1,  line 1016 in BMManager.py )
Also adding defining new landmarks on the body should help

Best
Diego

**Comment by jiawenzzz** [comment]
Thanks for you advice! I would try that :)
