### ISSUE TITLE
Transfer blendshapes defined by quad polygons (1 face defined by 4 vertices)

### ISSUE THREAD

**Issue by Neo1024** [diegothomas/Avatar-generation-3DRW2019-#3]
Hi, 

Thank you for this wonderful work and it's really handy! 

I an trying to apply this to other target avatar and I found that many 3D cartoon face models are define by quad polygons, i.e., a face consists of four vertices. This work is designed for triangular mesh based 3D models. I am wondering if the transformation method can somehow be quickly adapted for quad mesh based 3D models. Any suggestions? 
![image](https://user-images.githubusercontent.com/11141404/147184138-76b5d2d7-5038-4185-a112-b8cf286c01d3.png)

Br, 
Aaron

**Comment by diegothomas** [comment]
Hi Aaron,

thank you very much for your interest in our work!
To adapt the method for quad meshes, equations and corresponding code need to be modified.
I think the quickest way would be to make the quad mesh into a triangular mesh (simply divide each quad into 2 triangles) and then apply our method as it is on the generated triangular mesh.

best regards
Diego

**Comment by Neo1024** [comment]
> 

Thank you for the prompt reply! I actually came up with the same idea as the one you suggested and come to close this issue, and found that you've already replied :)
