### ISSUE TITLE
Blendshape semantics and 3D avatar resource

### ISSUE THREAD

**Issue by Neo1024** [diegothomas/Avatar-generation-3DRW2019-#5]
Hi Diego, 

I working on the facial motion retargeting topic. Now I am trying to convert the blendshapes you shared here to BFM model as well as other avatars. Overall, it looks good on BFM after the deformation transfer. However, there're some flaws on details. For example, the eyelid is not fully closed for the eye close blendshape. Since I am not a professional modeling artist, I don't know how to finetune it. 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/11141404/167131337-d5ad1709-c055-427a-9aa7-c23437b1aa1d.png">

I found some other blendshape resources of BFM model. I want to substitute some results by Blendshape Maker with those. For blendshapes of clear semantic meaning, it's easy to do, e.g., eye close BS. However, it's difficult for some other subtle BS. I am wondering do you have the description of the semantic meanings of the blendshapes, like [this](https://github.com/deepmo24/CPEM/blob/main/assets/blendshape_name.md), so that I can know what each BS is.

**Comment by Neo1024** [comment]
By the way, could you share where did you find the blendshapes and 3D model resources you used in the paper?

**Comment by diegothomas** [comment]
Hi Neo1024, 
Thank you for your interest in our work, and sorry for my late response.
About the details for the eye closed blendshape, I am sorry I am not a modeling artist neither and I do not know the best way to fine tune it. 
It sounds great to substitute our original blendshapes with more subtile ones. We downloaded our blendshape models from an old public dataset, which does not exist anymore.
Because our method is data driven we did not care much about the exact semantic meaning of each blendshape, which is lost now. I am sorry.

**Comment by TigerHix** [comment]
You may look at [ARKit's blend shapes](https://arkit-face-blendshapes.com/) for references to how those blend shapes should look like.

**Comment by diegothomas** [comment]
Thanks TigerHix! Yes blendshapes from [ARKit's blend shapes] look very similar to the ones we used in the project. You may need to confirm which mesh corresponds to which semantic. You can actually download them! http://blog.kiteandlightning.la/iphone-x-facial-capture-apple-blendshapes/ 
The only difference is that there is only the face (not the full head).

**Comment by Neo1024** [comment]
> You may look at [ARKit's blend shapes](https://arkit-face-blendshapes.com/) for references to how those blend shapes should look like.

I've actually found the obj files of ARkit blendshapes from this blog too.

**Comment by Neo1024** [comment]
> 

Thanks for the reply :) I checked the blendshapes one by one, comparing to the BS used by CPEM as well as ARkit. I concluded the information of blendshapes of corresponding semantic meaning here, with some exceptions that are not matched: 
![image](https://user-images.githubusercontent.com/11141404/170661753-54c34040-87fc-490c-a0f5-dbea081c0392.png)
