### ISSUE TITLE
Some differences between paper and code

### ISSUE THREAD

**Issue by LiZhenLiangLee** [diegothomas/Avatar-generation-3DRW2019-#6]
Hello, thanks for your amazing work.

In Section 4.3.2 of  your paper,  it mentioned  " To measure the size of each facial part, we first use the rotation  matrices Rk,s and Rk,t to align the facial part with the z axis."

In line 1481&1482，BMManager.py. In my understanding,  `Rot_S` and `Rot_A` is the rotation matrix  from z axis orientation to facial part normal vector orientation. So when we want to align the facial part with z axis,  we should apply the **inverse** rotation matrix `Rot_S.T` and `Rot_A.T` to each faical part's landmarks. 

However,  when measuring facial parts size (line 1486 to 1502  and line 1528 to 1544),  your code apply `Rot_S` and `Rot_A` to facial part landmarks instead of `Rot_S.T` and `Rot_A.T`. 

It makes me confused, hope you can give me some explanation

**Comment by diegothomas** [comment]
Hello,
Thank you very much for your interest in our work.

I am sorry Hayato was the person implementing the paper, so I am not 100% sure but it seems to me that you are right.
To compute the parts size we compute the bounding box of the facial parts in an aligned coordinate system. The facial parts are aligned with the z axis. 

Rot_S and Rot_A are obtained by minimizing the SN(AN)_Energy that transforms the (0,0,1) vector to local facial part orientation. Corresponds to equation (17) in the paper.
To make orientation vector back to the z axis, the inverse rotation should be used. 
Can you try l. 1481-1482?
            PartsRot_S[i] = Rot_S.T
            PartsRot_A[i] = Rot_A.T
If this works better then it is probably a bug in the code. Sorry about this.

**Comment by LiZhenLiangLee** [comment]
> Hello, thanks for your amazing work.
> 
> In Section 4.3.2 of your paper, it mentioned " To measure the size of each facial part, we first use the rotation matrices Rk,s and Rk,t to align the facial part with the z axis."
> 
> In line 1481&1482，BMManager.py. In my understanding, `Rot_S` and `Rot_A` is the rotation matrix from z axis orientation to facial part normal vector orientation. So when we want to align the facial part with z axis, we should apply the **inverse** rotation matrix `Rot_S.T` and `Rot_A.T` to each faical part's landmarks.
> 
> However, when measuring facial parts size (line 1486 to 1502 and line 1528 to 1544), your code apply `Rot_S` and `Rot_A` to facial part landmarks instead of `Rot_S.T` and `Rot_A.T`.
> 
> It makes me confused, hope you can give me some explanation

Thanks for your reply.

**Comment by LiZhenLiangLee** [comment]
> Hello, Thank you very much for your interest in our work.
> 
> I am sorry Hayato was the person implementing the paper, so I am not 100% sure but it seems to me that you are right. To compute the parts size we compute the bounding box of the facial parts in an aligned coordinate system. The facial parts are aligned with the z axis.
> 
> Rot_S and Rot_A are obtained by minimizing the SN(AN)_Energy that transforms the (0,0,1) vector to local facial part orientation. Corresponds to equation (17) in the paper. To make orientation vector back to the z axis, the inverse rotation should be used. Can you try l. 1481-1482? PartsRot_S[i] = Rot_S.T PartsRot_A[i] = Rot_A.T If this works better then it is probably a bug in the code. Sorry about this.

Thanks for your reply.
